/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Analysis {
    id: RecordId;
    owner: Principal;
    createdAt: Timestamp;
    verdict: Verdict;
    shelterId: RecordId;
    caption: string;
    siteId: RecordId;
    config: DesignConfig;
}
export interface AnalysisInput {
    verdict: Verdict;
    shelterId: RecordId;
    caption: string;
    siteId: RecordId;
    config: DesignConfig;
}
export interface AnalysisUpdate {
    verdict: Verdict;
    shelterId: RecordId;
    caption: string;
    siteId: RecordId;
    config: DesignConfig;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface DesignConfig {
    thermalMassCore: ThermalMassCore;
    insulationThicknessMm: bigint;
    windowToWallRatioPct: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type RecordId = bigint;
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Shelter {
    id: RecordId;
    floorAreaM2: number;
    foundationMode: FoundationMode;
    owner: Principal;
    name: string;
    createdAt: Timestamp;
    wallAreaWestM2: number;
    roofAreaM2: number;
    wallAreaNorthM2: number;
    orientationAzimuthDeg: number;
    sourcePreset?: string;
    wallAreaEastM2: number;
    sourceFileName?: string;
    wallAreaSouthM2: number;
    interiorVolumeM3: number;
}
export interface ShelterInput {
    floorAreaM2: number;
    foundationMode: FoundationMode;
    name: string;
    wallAreaWestM2: number;
    roofAreaM2: number;
    wallAreaNorthM2: number;
    orientationAzimuthDeg: number;
    sourcePreset?: string;
    wallAreaEastM2: number;
    sourceFileName?: string;
    wallAreaSouthM2: number;
    interiorVolumeM3: number;
}
export interface ShelterUpdate {
    floorAreaM2: number;
    foundationMode: FoundationMode;
    name: string;
    wallAreaWestM2: number;
    roofAreaM2: number;
    wallAreaNorthM2: number;
    orientationAzimuthDeg: number;
    sourcePreset?: string;
    wallAreaEastM2: number;
    sourceFileName?: string;
    wallAreaSouthM2: number;
    interiorVolumeM3: number;
}
export interface Site {
    id: RecordId;
    latitude: number;
    owner: Principal;
    createdAt: Timestamp;
    climateProfile: ClimateProfile;
    airDensityKgM3: number;
    climateEndNs: Timestamp;
    sector: Sector;
    climateStartNs: Timestamp;
    longitude: number;
    caption: string;
    altitudeM: number;
}
export interface SiteInput {
    latitude: number;
    climateProfile: ClimateProfile;
    airDensityKgM3: number;
    climateEndNs: Timestamp;
    sector: Sector;
    climateStartNs: Timestamp;
    longitude: number;
    caption: string;
    altitudeM: number;
}
export interface SiteUpdate {
    latitude: number;
    climateProfile: ClimateProfile;
    airDensityKgM3: number;
    climateEndNs: Timestamp;
    sector: Sector;
    climateStartNs: Timestamp;
    longitude: number;
    caption: string;
    altitudeM: number;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface Verdict {
    pmv: number;
    ppd: number;
    keroseneLitresPer24h: number;
    sapperManHours: number;
    airliftSorties: bigint;
    structuralWeightKg: number;
}
export enum ClimateProfile {
    compositeSummer = "compositeSummer",
    monsoonalTransition = "monsoonalTransition",
    extremeWinter = "extremeWinter"
}
export enum FoundationMode {
    elevatedSkids = "elevatedSkids",
    slabOnGrade = "slabOnGrade"
}
export enum Sector {
    northernSikkim = "northernSikkim",
    westernLadakh = "westernLadakh",
    tawang = "tawang",
    spitiKinnaur = "spitiKinnaur"
}
export enum ThermalMassCore {
    puf = "puf",
    vip = "vip",
    aerogel = "aerogel",
    adobe = "adobe",
    pcm28 = "pcm28"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Create a saved analysis for the caller.
     */
    createAnalysis(input: AnalysisInput): Promise<Analysis>;
    /**
     * / Create a saved shelter for the caller.
     */
    createShelter(input: ShelterInput): Promise<Shelter>;
    /**
     * / Create a saved site for the caller.
     */
    createSite(input: SiteInput): Promise<Site>;
    /**
     * / Delete one of the caller's saved analyses.
     */
    deleteAnalysis(id: RecordId): Promise<boolean>;
    /**
     * / Delete one of the caller's saved shelters.
     */
    deleteShelter(id: RecordId): Promise<boolean>;
    /**
     * / Delete one of the caller's saved sites.
     */
    deleteSite(id: RecordId): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Read one of the caller's saved analyses.
     */
    getAnalysis(id: RecordId): Promise<Analysis | null>;
    /**
     * / Static Markdown documentation of the backend's public API.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Read one of the caller's saved shelters.
     */
    getShelter(id: RecordId): Promise<Shelter | null>;
    /**
     * / Read one of the caller's saved sites.
     */
    getSite(id: RecordId): Promise<Site | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List the caller's saved analyses.
     */
    listAnalyses(): Promise<Array<Analysis>>;
    /**
     * / List the caller's saved shelters.
     */
    listShelters(): Promise<Array<Shelter>>;
    /**
     * / List the caller's saved sites.
     */
    listSites(): Promise<Array<Site>>;
    schema(): Promise<string>;
    /**
     * / Update one of the caller's saved analyses.
     */
    updateAnalysis(id: RecordId, input: AnalysisUpdate): Promise<Analysis | null>;
    /**
     * / Update one of the caller's saved shelters.
     */
    updateShelter(id: RecordId, input: ShelterUpdate): Promise<Shelter | null>;
    /**
     * / Update one of the caller's saved sites.
     */
    updateSite(id: RecordId, input: SiteUpdate): Promise<Site | null>;
}
import type { Analysis as _Analysis, AnalysisInput as _AnalysisInput, AnalysisUpdate as _AnalysisUpdate, Cell as _Cell, ClimateProfile as _ClimateProfile, DesignConfig as _DesignConfig, Error as _Error, FoundationMode as _FoundationMode, RecordId as _RecordId, Result as _Result, Result__1 as _Result__1, Sector as _Sector, Shelter as _Shelter, ShelterInput as _ShelterInput, ShelterUpdate as _ShelterUpdate, Site as _Site, SiteInput as _SiteInput, SiteUpdate as _SiteUpdate, ThermalMassCore as _ThermalMassCore, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value, Verdict as _Verdict } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAnalysis(arg0: AnalysisInput): Promise<Analysis> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnalysis(to_candid_AnalysisInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Analysis_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnalysis(to_candid_AnalysisInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Analysis_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createShelter(arg0: ShelterInput): Promise<Shelter> {
        if (this.processError) {
            try {
                const result = await this.actor.createShelter(to_candid_ShelterInput_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Shelter_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShelter(to_candid_ShelterInput_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Shelter_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSite(arg0: SiteInput): Promise<Site> {
        if (this.processError) {
            try {
                const result = await this.actor.createSite(to_candid_SiteInput_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Site_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSite(to_candid_SiteInput_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Site_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAnalysis(arg0: RecordId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnalysis(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnalysis(arg0);
            return result;
        }
    }
    async deleteShelter(arg0: RecordId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShelter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShelter(arg0);
            return result;
        }
    }
    async deleteSite(arg0: RecordId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSite(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysis(arg0: RecordId): Promise<Analysis | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysis(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysis(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShelter(arg0: RecordId): Promise<Shelter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShelter(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShelter(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSite(arg0: RecordId): Promise<Site | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSite(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSite(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAnalyses(): Promise<Array<Analysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnalyses();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnalyses();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listShelters(): Promise<Array<Shelter>> {
        if (this.processError) {
            try {
                const result = await this.actor.listShelters();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listShelters();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSites(): Promise<Array<Site>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSites();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSites();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async updateAnalysis(arg0: RecordId, arg1: AnalysisUpdate): Promise<Analysis | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnalysis(arg0, to_candid_AnalysisUpdate_n46(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnalysis(arg0, to_candid_AnalysisUpdate_n46(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateShelter(arg0: RecordId, arg1: ShelterUpdate): Promise<Shelter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShelter(arg0, to_candid_ShelterUpdate_n47(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShelter(arg0, to_candid_ShelterUpdate_n47(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSite(arg0: RecordId, arg1: SiteUpdate): Promise<Site | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSite(arg0, to_candid_SiteUpdate_n48(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSite(arg0, to_candid_SiteUpdate_n48(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Analysis_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Analysis): Analysis {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ClimateProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClimateProfile): ClimateProfile {
    return "compositeSummer" in value ? ClimateProfile.compositeSummer : "monsoonalTransition" in value ? ClimateProfile.monsoonalTransition : "extremeWinter" in value ? ClimateProfile.extremeWinter : value;
}
function from_candid_DesignConfig_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignConfig): DesignConfig {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_FoundationMode_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoundationMode): FoundationMode {
    return "elevatedSkids" in value ? FoundationMode.elevatedSkids : "slabOnGrade" in value ? FoundationMode.slabOnGrade : value;
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Sector_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sector): Sector {
    return "northernSikkim" in value ? Sector.northernSikkim : "westernLadakh" in value ? Sector.westernLadakh : "tawang" in value ? Sector.tawang : "spitiKinnaur" in value ? Sector.spitiKinnaur : value;
}
function from_candid_Shelter_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shelter): Shelter {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Site_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Site): Site {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ThermalMassCore_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThermalMassCore): ThermalMassCore {
    return "puf" in value ? ThermalMassCore.puf : "vip" in value ? ThermalMassCore.vip : "aerogel" in value ? ThermalMassCore.aerogel : "adobe" in value ? ThermalMassCore.adobe : "pcm28" in value ? ThermalMassCore.pcm28 : value;
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Analysis]): Analysis | null {
    return value.length === 0 ? null : from_candid_Analysis_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Shelter]): Shelter | null {
    return value.length === 0 ? null : from_candid_Shelter_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Site]): Site | null {
    return value.length === 0 ? null : from_candid_Site_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    owner: Principal;
    createdAt: _Timestamp;
    verdict: _Verdict;
    shelterId: _RecordId;
    caption: string;
    siteId: _RecordId;
    config: _DesignConfig;
}): {
    id: RecordId;
    owner: Principal;
    createdAt: Timestamp;
    verdict: Verdict;
    shelterId: RecordId;
    caption: string;
    siteId: RecordId;
    config: DesignConfig;
} {
    return {
        id: value.id,
        owner: value.owner,
        createdAt: value.createdAt,
        verdict: value.verdict,
        shelterId: value.shelterId,
        caption: value.caption,
        siteId: value.siteId,
        config: from_candid_DesignConfig_n13(_uploadFile, _downloadFile, value.config)
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    thermalMassCore: _ThermalMassCore;
    insulationThicknessMm: bigint;
    windowToWallRatioPct: bigint;
}): {
    thermalMassCore: ThermalMassCore;
    insulationThicknessMm: bigint;
    windowToWallRatioPct: bigint;
} {
    return {
        thermalMassCore: from_candid_ThermalMassCore_n15(_uploadFile, _downloadFile, value.thermalMassCore),
        insulationThicknessMm: value.insulationThicknessMm,
        windowToWallRatioPct: value.windowToWallRatioPct
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    floorAreaM2: number;
    foundationMode: _FoundationMode;
    owner: Principal;
    name: string;
    createdAt: _Timestamp;
    wallAreaWestM2: number;
    roofAreaM2: number;
    wallAreaNorthM2: number;
    orientationAzimuthDeg: number;
    sourcePreset: [] | [string];
    wallAreaEastM2: number;
    sourceFileName: [] | [string];
    wallAreaSouthM2: number;
    interiorVolumeM3: number;
}): {
    id: RecordId;
    floorAreaM2: number;
    foundationMode: FoundationMode;
    owner: Principal;
    name: string;
    createdAt: Timestamp;
    wallAreaWestM2: number;
    roofAreaM2: number;
    wallAreaNorthM2: number;
    orientationAzimuthDeg: number;
    sourcePreset?: string;
    wallAreaEastM2: number;
    sourceFileName?: string;
    wallAreaSouthM2: number;
    interiorVolumeM3: number;
} {
    return {
        id: value.id,
        floorAreaM2: value.floorAreaM2,
        foundationMode: from_candid_FoundationMode_n21(_uploadFile, _downloadFile, value.foundationMode),
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        wallAreaWestM2: value.wallAreaWestM2,
        roofAreaM2: value.roofAreaM2,
        wallAreaNorthM2: value.wallAreaNorthM2,
        orientationAzimuthDeg: value.orientationAzimuthDeg,
        sourcePreset: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.sourcePreset)),
        wallAreaEastM2: value.wallAreaEastM2,
        sourceFileName: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.sourceFileName)),
        wallAreaSouthM2: value.wallAreaSouthM2,
        interiorVolumeM3: value.interiorVolumeM3
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    latitude: number;
    owner: Principal;
    createdAt: _Timestamp;
    climateProfile: _ClimateProfile;
    airDensityKgM3: number;
    climateEndNs: _Timestamp;
    sector: _Sector;
    climateStartNs: _Timestamp;
    longitude: number;
    caption: string;
    altitudeM: number;
}): {
    id: RecordId;
    latitude: number;
    owner: Principal;
    createdAt: Timestamp;
    climateProfile: ClimateProfile;
    airDensityKgM3: number;
    climateEndNs: Timestamp;
    sector: Sector;
    climateStartNs: Timestamp;
    longitude: number;
    caption: string;
    altitudeM: number;
} {
    return {
        id: value.id,
        latitude: value.latitude,
        owner: value.owner,
        createdAt: value.createdAt,
        climateProfile: from_candid_ClimateProfile_n29(_uploadFile, _downloadFile, value.climateProfile),
        airDensityKgM3: value.airDensityKgM3,
        climateEndNs: value.climateEndNs,
        sector: from_candid_Sector_n30(_uploadFile, _downloadFile, value.sector),
        climateStartNs: value.climateStartNs,
        longitude: value.longitude,
        caption: value.caption,
        altitudeM: value.altitudeM
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n33(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n37(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Analysis>): Array<Analysis> {
    return value.map((x)=>from_candid_Analysis_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Shelter>): Array<Shelter> {
    return value.map((x)=>from_candid_Shelter_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Site>): Array<Site> {
    return value.map((x)=>from_candid_Site_n27(_uploadFile, _downloadFile, x));
}
function to_candid_AnalysisInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisInput): _AnalysisInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_AnalysisUpdate_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisUpdate): _AnalysisUpdate {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_ClimateProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClimateProfile): _ClimateProfile {
    return value == ClimateProfile.compositeSummer ? {
        compositeSummer: null
    } : value == ClimateProfile.monsoonalTransition ? {
        monsoonalTransition: null
    } : value == ClimateProfile.extremeWinter ? {
        extremeWinter: null
    } : value;
}
function to_candid_DesignConfig_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignConfig): _DesignConfig {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_FoundationMode_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoundationMode): _FoundationMode {
    return value == FoundationMode.elevatedSkids ? {
        elevatedSkids: null
    } : value == FoundationMode.slabOnGrade ? {
        slabOnGrade: null
    } : value;
}
function to_candid_Sector_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sector): _Sector {
    return value == Sector.northernSikkim ? {
        northernSikkim: null
    } : value == Sector.westernLadakh ? {
        westernLadakh: null
    } : value == Sector.tawang ? {
        tawang: null
    } : value == Sector.spitiKinnaur ? {
        spitiKinnaur: null
    } : value;
}
function to_candid_ShelterInput_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShelterInput): _ShelterInput {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_ShelterUpdate_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShelterUpdate): _ShelterUpdate {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_SiteInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteInput): _SiteInput {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_SiteUpdate_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteUpdate): _SiteUpdate {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_ThermalMassCore_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThermalMassCore): _ThermalMassCore {
    return value == ThermalMassCore.puf ? {
        puf: null
    } : value == ThermalMassCore.vip ? {
        vip: null
    } : value == ThermalMassCore.aerogel ? {
        aerogel: null
    } : value == ThermalMassCore.adobe ? {
        adobe: null
    } : value == ThermalMassCore.pcm28 ? {
        pcm28: null
    } : value;
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    floorAreaM2: number;
    foundationMode: FoundationMode;
    name: string;
    wallAreaWestM2: number;
    roofAreaM2: number;
    wallAreaNorthM2: number;
    orientationAzimuthDeg: number;
    sourcePreset?: string;
    wallAreaEastM2: number;
    sourceFileName?: string;
    wallAreaSouthM2: number;
    interiorVolumeM3: number;
}): {
    floorAreaM2: number;
    foundationMode: _FoundationMode;
    name: string;
    wallAreaWestM2: number;
    roofAreaM2: number;
    wallAreaNorthM2: number;
    orientationAzimuthDeg: number;
    sourcePreset: [] | [string];
    wallAreaEastM2: number;
    sourceFileName: [] | [string];
    wallAreaSouthM2: number;
    interiorVolumeM3: number;
} {
    return {
        floorAreaM2: value.floorAreaM2,
        foundationMode: to_candid_FoundationMode_n18(_uploadFile, _downloadFile, value.foundationMode),
        name: value.name,
        wallAreaWestM2: value.wallAreaWestM2,
        roofAreaM2: value.roofAreaM2,
        wallAreaNorthM2: value.wallAreaNorthM2,
        orientationAzimuthDeg: value.orientationAzimuthDeg,
        sourcePreset: value.sourcePreset ? candid_some(value.sourcePreset) : candid_none(),
        wallAreaEastM2: value.wallAreaEastM2,
        sourceFileName: value.sourceFileName ? candid_some(value.sourceFileName) : candid_none(),
        wallAreaSouthM2: value.wallAreaSouthM2,
        interiorVolumeM3: value.interiorVolumeM3
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: number;
    climateProfile: ClimateProfile;
    airDensityKgM3: number;
    climateEndNs: Timestamp;
    sector: Sector;
    climateStartNs: Timestamp;
    longitude: number;
    caption: string;
    altitudeM: number;
}): {
    latitude: number;
    climateProfile: _ClimateProfile;
    airDensityKgM3: number;
    climateEndNs: _Timestamp;
    sector: _Sector;
    climateStartNs: _Timestamp;
    longitude: number;
    caption: string;
    altitudeM: number;
} {
    return {
        latitude: value.latitude,
        climateProfile: to_candid_ClimateProfile_n25(_uploadFile, _downloadFile, value.climateProfile),
        airDensityKgM3: value.airDensityKgM3,
        climateEndNs: value.climateEndNs,
        sector: to_candid_Sector_n26(_uploadFile, _downloadFile, value.sector),
        climateStartNs: value.climateStartNs,
        longitude: value.longitude,
        caption: value.caption,
        altitudeM: value.altitudeM
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verdict: Verdict;
    shelterId: RecordId;
    caption: string;
    siteId: RecordId;
    config: DesignConfig;
}): {
    verdict: _Verdict;
    shelterId: _RecordId;
    caption: string;
    siteId: _RecordId;
    config: _DesignConfig;
} {
    return {
        verdict: value.verdict,
        shelterId: value.shelterId,
        caption: value.caption,
        siteId: value.siteId,
        config: to_candid_DesignConfig_n8(_uploadFile, _downloadFile, value.config)
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    thermalMassCore: ThermalMassCore;
    insulationThicknessMm: bigint;
    windowToWallRatioPct: bigint;
}): {
    thermalMassCore: _ThermalMassCore;
    insulationThicknessMm: bigint;
    windowToWallRatioPct: bigint;
} {
    return {
        thermalMassCore: to_candid_ThermalMassCore_n10(_uploadFile, _downloadFile, value.thermalMassCore),
        insulationThicknessMm: value.insulationThicknessMm,
        windowToWallRatioPct: value.windowToWallRatioPct
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
