# THERMIS — PyANSYS Export Script
# Generated by THERMIS SIH26051
# Use with: PyANSYS Fluent / Mechanical

import ansys.fluent.core as pyfluent
import numpy as np

# ─── SHELTER GEOMETRY ─────────────────────────────────────────────
SHELTER_LENGTH = 6.0   # m
SHELTER_WIDTH  = 4.0   # m
SHELTER_HEIGHT = 2.5   # m
WWR            = 0.10  # Window-to-Wall Ratio

# ─── MATERIAL PROPERTIES ──────────────────────────────────────────
WALL_U_VALUE   = 0.35  # W/m²K
ROOF_U_VALUE   = 0.30
FLOOR_U_VALUE  = 0.45
ROOF_ABS       = 0.85  # Solar absorptivity

# ─── BOUNDARY CONDITIONS ──────────────────────────────────────────
T_AMBIENT      = -25.0  # °C (design winter minimum)
T_GROUND       = 2.0    # °C (permafrost)
WIND_SPEED     = 8.0    # m/s
ACH            = 1.2    # Air changes per hour

# ─── McAdams External Convection ──────────────────────────────────
h_c = 10.45 + 10 * np.sqrt(WIND_SPEED)
print(f"h_c (McAdams) = {h_c:.2f} W/m²K")

# ─── Air Density Correction ───────────────────────────────────────
ELEVATION = 3500  # m (Leh, Ladakh)
rho = 1.225 * np.exp(-9.80665 * 0.0289644 * ELEVATION / (8.31446 * (T_AMBIENT + 273.15)))
print(f"Air density at {ELEVATION}m = {rho:.4f} kg/m³")

# ─── Launch Fluent ────────────────────────────────────────────────
# solver = pyfluent.launch_fluent(precision="double", processor_count=4)
# session = solver.start_transcript()

# ─── Define Domain ────────────────────────────────────────────────
# geometry = session.tui.define.geometry
# (define shelter solid + fluid domain)

print("THERMIS PyANSYS template — configure and run with Fluent")
print("Generated by THERMIS SIH26051")
