/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Verdict = IDL.Record({
  'pmv' : IDL.Float64,
  'ppd' : IDL.Float64,
  'keroseneLitresPer24h' : IDL.Float64,
  'sapperManHours' : IDL.Float64,
  'airliftSorties' : IDL.Nat,
  'structuralWeightKg' : IDL.Float64,
});
export const RecordId = IDL.Nat;
export const ThermalMassCore = IDL.Variant({
  'puf' : IDL.Null,
  'vip' : IDL.Null,
  'aerogel' : IDL.Null,
  'adobe' : IDL.Null,
  'pcm28' : IDL.Null,
});
export const DesignConfig = IDL.Record({
  'thermalMassCore' : ThermalMassCore,
  'insulationThicknessMm' : IDL.Nat,
  'windowToWallRatioPct' : IDL.Nat,
});
export const AnalysisInput = IDL.Record({
  'verdict' : Verdict,
  'shelterId' : RecordId,
  'caption' : IDL.Text,
  'siteId' : RecordId,
  'config' : DesignConfig,
});
export const Timestamp = IDL.Int;
export const Analysis = IDL.Record({
  'id' : RecordId,
  'owner' : IDL.Principal,
  'createdAt' : Timestamp,
  'verdict' : Verdict,
  'shelterId' : RecordId,
  'caption' : IDL.Text,
  'siteId' : RecordId,
  'config' : DesignConfig,
});
export const FoundationMode = IDL.Variant({
  'elevatedSkids' : IDL.Null,
  'slabOnGrade' : IDL.Null,
});
export const ShelterInput = IDL.Record({
  'floorAreaM2' : IDL.Float64,
  'foundationMode' : FoundationMode,
  'name' : IDL.Text,
  'wallAreaWestM2' : IDL.Float64,
  'roofAreaM2' : IDL.Float64,
  'wallAreaNorthM2' : IDL.Float64,
  'orientationAzimuthDeg' : IDL.Float64,
  'sourcePreset' : IDL.Opt(IDL.Text),
  'wallAreaEastM2' : IDL.Float64,
  'sourceFileName' : IDL.Opt(IDL.Text),
  'wallAreaSouthM2' : IDL.Float64,
  'interiorVolumeM3' : IDL.Float64,
});
export const Shelter = IDL.Record({
  'id' : RecordId,
  'floorAreaM2' : IDL.Float64,
  'foundationMode' : FoundationMode,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'wallAreaWestM2' : IDL.Float64,
  'roofAreaM2' : IDL.Float64,
  'wallAreaNorthM2' : IDL.Float64,
  'orientationAzimuthDeg' : IDL.Float64,
  'sourcePreset' : IDL.Opt(IDL.Text),
  'wallAreaEastM2' : IDL.Float64,
  'sourceFileName' : IDL.Opt(IDL.Text),
  'wallAreaSouthM2' : IDL.Float64,
  'interiorVolumeM3' : IDL.Float64,
});
export const ClimateProfile = IDL.Variant({
  'compositeSummer' : IDL.Null,
  'monsoonalTransition' : IDL.Null,
  'extremeWinter' : IDL.Null,
});
export const Sector = IDL.Variant({
  'northernSikkim' : IDL.Null,
  'westernLadakh' : IDL.Null,
  'tawang' : IDL.Null,
  'spitiKinnaur' : IDL.Null,
});
export const SiteInput = IDL.Record({
  'latitude' : IDL.Float64,
  'climateProfile' : ClimateProfile,
  'airDensityKgM3' : IDL.Float64,
  'climateEndNs' : Timestamp,
  'sector' : Sector,
  'climateStartNs' : Timestamp,
  'longitude' : IDL.Float64,
  'caption' : IDL.Text,
  'altitudeM' : IDL.Float64,
});
export const Site = IDL.Record({
  'id' : RecordId,
  'latitude' : IDL.Float64,
  'owner' : IDL.Principal,
  'createdAt' : Timestamp,
  'climateProfile' : ClimateProfile,
  'airDensityKgM3' : IDL.Float64,
  'climateEndNs' : Timestamp,
  'sector' : Sector,
  'climateStartNs' : Timestamp,
  'longitude' : IDL.Float64,
  'caption' : IDL.Text,
  'altitudeM' : IDL.Float64,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AnalysisUpdate = IDL.Record({
  'verdict' : Verdict,
  'shelterId' : RecordId,
  'caption' : IDL.Text,
  'siteId' : RecordId,
  'config' : DesignConfig,
});
export const ShelterUpdate = IDL.Record({
  'floorAreaM2' : IDL.Float64,
  'foundationMode' : FoundationMode,
  'name' : IDL.Text,
  'wallAreaWestM2' : IDL.Float64,
  'roofAreaM2' : IDL.Float64,
  'wallAreaNorthM2' : IDL.Float64,
  'orientationAzimuthDeg' : IDL.Float64,
  'sourcePreset' : IDL.Opt(IDL.Text),
  'wallAreaEastM2' : IDL.Float64,
  'sourceFileName' : IDL.Opt(IDL.Text),
  'wallAreaSouthM2' : IDL.Float64,
  'interiorVolumeM3' : IDL.Float64,
});
export const SiteUpdate = IDL.Record({
  'latitude' : IDL.Float64,
  'climateProfile' : ClimateProfile,
  'airDensityKgM3' : IDL.Float64,
  'climateEndNs' : Timestamp,
  'sector' : Sector,
  'climateStartNs' : Timestamp,
  'longitude' : IDL.Float64,
  'caption' : IDL.Text,
  'altitudeM' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnalysis' : IDL.Func([AnalysisInput], [Analysis], []),
  'createShelter' : IDL.Func([ShelterInput], [Shelter], []),
  'createSite' : IDL.Func([SiteInput], [Site], []),
  'deleteAnalysis' : IDL.Func([RecordId], [IDL.Bool], []),
  'deleteShelter' : IDL.Func([RecordId], [IDL.Bool], []),
  'deleteSite' : IDL.Func([RecordId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAnalysis' : IDL.Func([RecordId], [IDL.Opt(Analysis)], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getShelter' : IDL.Func([RecordId], [IDL.Opt(Shelter)], []),
  'getSite' : IDL.Func([RecordId], [IDL.Opt(Site)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAnalyses' : IDL.Func([], [IDL.Vec(Analysis)], []),
  'listShelters' : IDL.Func([], [IDL.Vec(Shelter)], []),
  'listSites' : IDL.Func([], [IDL.Vec(Site)], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateAnalysis' : IDL.Func(
      [RecordId, AnalysisUpdate],
      [IDL.Opt(Analysis)],
      [],
    ),
  'updateShelter' : IDL.Func([RecordId, ShelterUpdate], [IDL.Opt(Shelter)], []),
  'updateSite' : IDL.Func([RecordId, SiteUpdate], [IDL.Opt(Site)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Verdict = IDL.Record({
    'pmv' : IDL.Float64,
    'ppd' : IDL.Float64,
    'keroseneLitresPer24h' : IDL.Float64,
    'sapperManHours' : IDL.Float64,
    'airliftSorties' : IDL.Nat,
    'structuralWeightKg' : IDL.Float64,
  });
  const RecordId = IDL.Nat;
  const ThermalMassCore = IDL.Variant({
    'puf' : IDL.Null,
    'vip' : IDL.Null,
    'aerogel' : IDL.Null,
    'adobe' : IDL.Null,
    'pcm28' : IDL.Null,
  });
  const DesignConfig = IDL.Record({
    'thermalMassCore' : ThermalMassCore,
    'insulationThicknessMm' : IDL.Nat,
    'windowToWallRatioPct' : IDL.Nat,
  });
  const AnalysisInput = IDL.Record({
    'verdict' : Verdict,
    'shelterId' : RecordId,
    'caption' : IDL.Text,
    'siteId' : RecordId,
    'config' : DesignConfig,
  });
  const Timestamp = IDL.Int;
  const Analysis = IDL.Record({
    'id' : RecordId,
    'owner' : IDL.Principal,
    'createdAt' : Timestamp,
    'verdict' : Verdict,
    'shelterId' : RecordId,
    'caption' : IDL.Text,
    'siteId' : RecordId,
    'config' : DesignConfig,
  });
  const FoundationMode = IDL.Variant({
    'elevatedSkids' : IDL.Null,
    'slabOnGrade' : IDL.Null,
  });
  const ShelterInput = IDL.Record({
    'floorAreaM2' : IDL.Float64,
    'foundationMode' : FoundationMode,
    'name' : IDL.Text,
    'wallAreaWestM2' : IDL.Float64,
    'roofAreaM2' : IDL.Float64,
    'wallAreaNorthM2' : IDL.Float64,
    'orientationAzimuthDeg' : IDL.Float64,
    'sourcePreset' : IDL.Opt(IDL.Text),
    'wallAreaEastM2' : IDL.Float64,
    'sourceFileName' : IDL.Opt(IDL.Text),
    'wallAreaSouthM2' : IDL.Float64,
    'interiorVolumeM3' : IDL.Float64,
  });
  const Shelter = IDL.Record({
    'id' : RecordId,
    'floorAreaM2' : IDL.Float64,
    'foundationMode' : FoundationMode,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'wallAreaWestM2' : IDL.Float64,
    'roofAreaM2' : IDL.Float64,
    'wallAreaNorthM2' : IDL.Float64,
    'orientationAzimuthDeg' : IDL.Float64,
    'sourcePreset' : IDL.Opt(IDL.Text),
    'wallAreaEastM2' : IDL.Float64,
    'sourceFileName' : IDL.Opt(IDL.Text),
    'wallAreaSouthM2' : IDL.Float64,
    'interiorVolumeM3' : IDL.Float64,
  });
  const ClimateProfile = IDL.Variant({
    'compositeSummer' : IDL.Null,
    'monsoonalTransition' : IDL.Null,
    'extremeWinter' : IDL.Null,
  });
  const Sector = IDL.Variant({
    'northernSikkim' : IDL.Null,
    'westernLadakh' : IDL.Null,
    'tawang' : IDL.Null,
    'spitiKinnaur' : IDL.Null,
  });
  const SiteInput = IDL.Record({
    'latitude' : IDL.Float64,
    'climateProfile' : ClimateProfile,
    'airDensityKgM3' : IDL.Float64,
    'climateEndNs' : Timestamp,
    'sector' : Sector,
    'climateStartNs' : Timestamp,
    'longitude' : IDL.Float64,
    'caption' : IDL.Text,
    'altitudeM' : IDL.Float64,
  });
  const Site = IDL.Record({
    'id' : RecordId,
    'latitude' : IDL.Float64,
    'owner' : IDL.Principal,
    'createdAt' : Timestamp,
    'climateProfile' : ClimateProfile,
    'airDensityKgM3' : IDL.Float64,
    'climateEndNs' : Timestamp,
    'sector' : Sector,
    'climateStartNs' : Timestamp,
    'longitude' : IDL.Float64,
    'caption' : IDL.Text,
    'altitudeM' : IDL.Float64,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AnalysisUpdate = IDL.Record({
    'verdict' : Verdict,
    'shelterId' : RecordId,
    'caption' : IDL.Text,
    'siteId' : RecordId,
    'config' : DesignConfig,
  });
  const ShelterUpdate = IDL.Record({
    'floorAreaM2' : IDL.Float64,
    'foundationMode' : FoundationMode,
    'name' : IDL.Text,
    'wallAreaWestM2' : IDL.Float64,
    'roofAreaM2' : IDL.Float64,
    'wallAreaNorthM2' : IDL.Float64,
    'orientationAzimuthDeg' : IDL.Float64,
    'sourcePreset' : IDL.Opt(IDL.Text),
    'wallAreaEastM2' : IDL.Float64,
    'sourceFileName' : IDL.Opt(IDL.Text),
    'wallAreaSouthM2' : IDL.Float64,
    'interiorVolumeM3' : IDL.Float64,
  });
  const SiteUpdate = IDL.Record({
    'latitude' : IDL.Float64,
    'climateProfile' : ClimateProfile,
    'airDensityKgM3' : IDL.Float64,
    'climateEndNs' : Timestamp,
    'sector' : Sector,
    'climateStartNs' : Timestamp,
    'longitude' : IDL.Float64,
    'caption' : IDL.Text,
    'altitudeM' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnalysis' : IDL.Func([AnalysisInput], [Analysis], []),
    'createShelter' : IDL.Func([ShelterInput], [Shelter], []),
    'createSite' : IDL.Func([SiteInput], [Site], []),
    'deleteAnalysis' : IDL.Func([RecordId], [IDL.Bool], []),
    'deleteShelter' : IDL.Func([RecordId], [IDL.Bool], []),
    'deleteSite' : IDL.Func([RecordId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAnalysis' : IDL.Func([RecordId], [IDL.Opt(Analysis)], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getShelter' : IDL.Func([RecordId], [IDL.Opt(Shelter)], []),
    'getSite' : IDL.Func([RecordId], [IDL.Opt(Site)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAnalyses' : IDL.Func([], [IDL.Vec(Analysis)], []),
    'listShelters' : IDL.Func([], [IDL.Vec(Shelter)], []),
    'listSites' : IDL.Func([], [IDL.Vec(Site)], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateAnalysis' : IDL.Func(
        [RecordId, AnalysisUpdate],
        [IDL.Opt(Analysis)],
        [],
      ),
    'updateShelter' : IDL.Func(
        [RecordId, ShelterUpdate],
        [IDL.Opt(Shelter)],
        [],
      ),
    'updateSite' : IDL.Func([RecordId, SiteUpdate], [IDL.Opt(Site)], []),
  });
};

export const init = ({ IDL }) => { return []; };