/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analysis {
  'id' : RecordId,
  'owner' : Principal,
  'createdAt' : Timestamp,
  'verdict' : Verdict,
  'shelterId' : RecordId,
  'caption' : string,
  'siteId' : RecordId,
  'config' : DesignConfig,
}
export interface AnalysisInput {
  'verdict' : Verdict,
  'shelterId' : RecordId,
  'caption' : string,
  'siteId' : RecordId,
  'config' : DesignConfig,
}
export interface AnalysisUpdate {
  'verdict' : Verdict,
  'shelterId' : RecordId,
  'caption' : string,
  'siteId' : RecordId,
  'config' : DesignConfig,
}
export interface Cell { 'value' : Value, 'name' : string }
export type ClimateProfile = { 'compositeSummer' : null } |
  { 'monsoonalTransition' : null } |
  { 'extremeWinter' : null };
export interface DesignConfig {
  'thermalMassCore' : ThermalMassCore,
  'insulationThicknessMm' : bigint,
  'windowToWallRatioPct' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type FoundationMode = { 'elevatedSkids' : null } |
  { 'slabOnGrade' : null };
export type RecordId = bigint;
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Sector = { 'northernSikkim' : null } |
  { 'westernLadakh' : null } |
  { 'tawang' : null } |
  { 'spitiKinnaur' : null };
export interface Shelter {
  'id' : RecordId,
  'floorAreaM2' : number,
  'foundationMode' : FoundationMode,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'wallAreaWestM2' : number,
  'roofAreaM2' : number,
  'wallAreaNorthM2' : number,
  'orientationAzimuthDeg' : number,
  'sourcePreset' : [] | [string],
  'wallAreaEastM2' : number,
  'sourceFileName' : [] | [string],
  'wallAreaSouthM2' : number,
  'interiorVolumeM3' : number,
}
export interface ShelterInput {
  'floorAreaM2' : number,
  'foundationMode' : FoundationMode,
  'name' : string,
  'wallAreaWestM2' : number,
  'roofAreaM2' : number,
  'wallAreaNorthM2' : number,
  'orientationAzimuthDeg' : number,
  'sourcePreset' : [] | [string],
  'wallAreaEastM2' : number,
  'sourceFileName' : [] | [string],
  'wallAreaSouthM2' : number,
  'interiorVolumeM3' : number,
}
export interface ShelterUpdate {
  'floorAreaM2' : number,
  'foundationMode' : FoundationMode,
  'name' : string,
  'wallAreaWestM2' : number,
  'roofAreaM2' : number,
  'wallAreaNorthM2' : number,
  'orientationAzimuthDeg' : number,
  'sourcePreset' : [] | [string],
  'wallAreaEastM2' : number,
  'sourceFileName' : [] | [string],
  'wallAreaSouthM2' : number,
  'interiorVolumeM3' : number,
}
export interface Site {
  'id' : RecordId,
  'latitude' : number,
  'owner' : Principal,
  'createdAt' : Timestamp,
  'climateProfile' : ClimateProfile,
  'airDensityKgM3' : number,
  'climateEndNs' : Timestamp,
  'sector' : Sector,
  'climateStartNs' : Timestamp,
  'longitude' : number,
  'caption' : string,
  'altitudeM' : number,
}
export interface SiteInput {
  'latitude' : number,
  'climateProfile' : ClimateProfile,
  'airDensityKgM3' : number,
  'climateEndNs' : Timestamp,
  'sector' : Sector,
  'climateStartNs' : Timestamp,
  'longitude' : number,
  'caption' : string,
  'altitudeM' : number,
}
export interface SiteUpdate {
  'latitude' : number,
  'climateProfile' : ClimateProfile,
  'airDensityKgM3' : number,
  'climateEndNs' : Timestamp,
  'sector' : Sector,
  'climateStartNs' : Timestamp,
  'longitude' : number,
  'caption' : string,
  'altitudeM' : number,
}
export type ThermalMassCore = { 'puf' : null } |
  { 'vip' : null } |
  { 'aerogel' : null } |
  { 'adobe' : null } |
  { 'pcm28' : null };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface Verdict {
  'pmv' : number,
  'ppd' : number,
  'keroseneLitresPer24h' : number,
  'sapperManHours' : number,
  'airliftSorties' : bigint,
  'structuralWeightKg' : number,
}
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a saved analysis for the caller.
   */
  'createAnalysis' : ActorMethod<[AnalysisInput], Analysis>,
  /**
   * / Create a saved shelter for the caller.
   */
  'createShelter' : ActorMethod<[ShelterInput], Shelter>,
  /**
   * / Create a saved site for the caller.
   */
  'createSite' : ActorMethod<[SiteInput], Site>,
  /**
   * / Delete one of the caller's saved analyses.
   */
  'deleteAnalysis' : ActorMethod<[RecordId], boolean>,
  /**
   * / Delete one of the caller's saved shelters.
   */
  'deleteShelter' : ActorMethod<[RecordId], boolean>,
  /**
   * / Delete one of the caller's saved sites.
   */
  'deleteSite' : ActorMethod<[RecordId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Read one of the caller's saved analyses.
   */
  'getAnalysis' : ActorMethod<[RecordId], [] | [Analysis]>,
  /**
   * / Static Markdown documentation of the backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Read one of the caller's saved shelters.
   */
  'getShelter' : ActorMethod<[RecordId], [] | [Shelter]>,
  /**
   * / Read one of the caller's saved sites.
   */
  'getSite' : ActorMethod<[RecordId], [] | [Site]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the caller's saved analyses.
   */
  'listAnalyses' : ActorMethod<[], Array<Analysis>>,
  /**
   * / List the caller's saved shelters.
   */
  'listShelters' : ActorMethod<[], Array<Shelter>>,
  /**
   * / List the caller's saved sites.
   */
  'listSites' : ActorMethod<[], Array<Site>>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Update one of the caller's saved analyses.
   */
  'updateAnalysis' : ActorMethod<[RecordId, AnalysisUpdate], [] | [Analysis]>,
  /**
   * / Update one of the caller's saved shelters.
   */
  'updateShelter' : ActorMethod<[RecordId, ShelterUpdate], [] | [Shelter]>,
  /**
   * / Update one of the caller's saved sites.
   */
  'updateSite' : ActorMethod<[RecordId, SiteUpdate], [] | [Site]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];